<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWU99xQn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWU99xQn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWU99xQn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWU99xQn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWU99xQn\App_KernelDevDebugContainer([
    'container.build_hash' => 'WU99xQn',
    'container.build_id' => '4f707eb5',
    'container.build_time' => 1605540668,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWU99xQn');
