<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAp6q8je\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAp6q8je/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAp6q8je.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAp6q8je\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAp6q8je\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ap6q8je',
    'container.build_id' => '6d0df679',
    'container.build_time' => 1605544810,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAp6q8je');
